plugins {
	// loom plugin
	id "fabric-loom" version "${loom_version}"
	id "ploceus" version "${loom_version}"
	id "com.diffplug.spotless" version "8.6.0"
}

// set basic properties
def hash = ""
if(project.release=="false") {
	hash = "-SNAPSHOT_"+getGitCommitHash()
}
version = project.version+hash
group = project.group

base {
	archivesName = project.artifact
}

java {
	// compile for java 8
	sourceCompatibility = targetCompatibility = 8
}

loom {
	// set access widener
	accessWidenerPath = file("src/main/resources/tasmod.accesswidener")
	// add log4jconfig
	log4jConfigs.from(file("src/main/resources/log4j.xml"))
}

// dependency repositories
repositories {
	mavenCentral()
	maven { url = "https://maven.minecrafttas.com/main" }
	//maven { url = "https://maven.minecrafttas.com/snapshots" }
	maven { url = "https://jitpack.io" }
	maven { url = "https://repo.spongepowered.org/maven" }
}

// dependency configurations
configurations {
	// embed dependency included in build
	implementation.extendsFrom(embed)
}

ploceus {
	setIntermediaryGeneration(1)
}

// dependencies
dependencies {
	// tasmod dependencies
	embed "com.dselent:bigarraylist:1.6"
	embed "com.github.KaptainWutax:SeedUtils:b6a383113c"
	implementation "com.google.code.gson:gson:2.14.0"
	
	// loom dependencies
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings ploceus.mcpMappings(project.mcp_channel, project.mcp_mcversion, project.mcp_build)
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// testing dependencies
	testImplementation "org.junit.jupiter:junit-jupiter:5.14.1"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}


compileJava {
	options.release = 8
}

// process fabric mod json
processResources {
	inputs.property "version", project.version
	inputs.property "mcversion", project.minecraft_version

	filesMatching("fabric.mod.json") {
		expand "mod_url": project.mod_url, "name": project.mod_name, "mod_version": project.version, "mod_description": project.mod_description, "mod_sources": project.mod_sources, "mod_email": project.mod_email
	}
}

// configure jar file
jar {

	// pack embedded stuff
	from {
		configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
	} {
		exclude "LICENSE.txt", "META-INF/MANIFSET.MF", "META-INF/maven/**", "META-INF/*.RSA", "META-INF/*.SF"
    }
}

// configure testing
tasks.named("test", Test) {
	useJUnitPlatform()

	testLogging {
		events "passed", "skipped", "failed"
	}
}

spotless {
	encoding "UTF-8"
	lineEndings "UNIX"
	java {
		importOrderFile("formatter/TASmodImportorder.txt")
		eclipse().configFile("formatter/TASmodFormatter.xml")
	}
	enforceCheck false
}

def getGitCommitHash() {
    def gitFolder = "$projectDir/.git/"
    def takeFromHash = 7
    /*
     * '.git/HEAD' contains either
     *      in case of detached head: the currently checked out commit hash
     *      otherwise: a reference to a file containing the current commit hash
     */
    def head = new File(gitFolder + "HEAD").text.split(":") // .git/HEAD
    def isCommit = head.length == 1
    // def isRef = head.length > 1     // ref: refs/heads/master

    if(isCommit) return head[0].trim().take(takeFromHash) // e5a7c79edabb

    def refHead = new File(gitFolder + head[1].trim()) // .git/refs/heads/master
    refHead.text.trim().take takeFromHash      
}