pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            url = 'https://maven.minecrafttas.com/main'
        }
        maven { url = 'https://maven.legacyfabric.net/' }
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://repo.spongepowered.org/maven' }
        mavenCentral()
        gradlePluginPortal()
    }
}
