# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.4
    - name: Build TASmod with Gradle
      run: gradle build
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: TestResult
        path: build/test-results/test/*.xml
    - name: Upload TASmod-Dev-Build
      uses: actions/upload-artifact@v4
      with:
        name: TASmod-Dev-Build
        path: build/libs
