# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Upload to Discord

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'MinecraftTAS/TASmod'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.4
    - name: Build TASmod with Gradle
      run: gradle build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TASmod-Dev-Build
        path: build/libs
    - name: Send file to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: build/libs/TASmod-*.jar