# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Upload to Discord

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Set up JDK 8 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.0
      with:
        gradle-version: 4.10.3
    - name: Build TASmod with Gradle
      run: gradle shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: TASmod-Dev-Build
        path: build/libs

  send-to-discord:
    runs-on: ubuntu-latest
    needs: build
    if:
      github.repository == 'MinecraftTAS/TASmod' && github.triggering_actor == 'ScribbleLP'
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3.0.2
    - name: Send file to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: TASmod-*.jar

    
